version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - ./.env

  web:
    image: alibekubaidullayev/foodgram:v1_backend
    volumes:
      - static_value:/app/django/static/
      - media_value:/app/django/media/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: alibekubaidullayev/foodgram:v1_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/django/static/
      - media_value:/var/html/django/media/
    depends_on:
      - frontend

volumes:
  db:
  result_build:
  static_value:
  media_value:
