# Generated by Django 4.1 on 2022-09-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_ingredients_ingredientrecipe_recipe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="owner",
            new_name="user",
        ),
    ]
