# Generated by Django 4.1 on 2022-09-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="tmp_media/", verbose_name="Image"
            ),
        ),
    ]
