# Generated by Django 4.1 on 2022-09-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_rename_unit_ingredient_measurement_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="hexcolor",
            new_name="color",
        ),
    ]
