# Generated by Django 4.1 on 2022-09-16 04:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0009_alter_ingredientrecipe_ingredient_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorite",
            name="unique_favorite",
        ),
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique_follow",
        ),
        migrations.RemoveConstraint(
            model_name="ingredientrecipe",
            name="ingredients_recipe",
        ),
        migrations.RemoveConstraint(
            model_name="shoppingcart",
            name="unique_shopping_cart",
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "recipe")},
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "following")},
        ),
        migrations.AlterUniqueTogether(
            name="ingredientrecipe",
            unique_together={("ingredient", "recipe")},
        ),
        migrations.AlterUniqueTogether(
            name="shoppingcart",
            unique_together={("user", "recipe")},
        ),
    ]
