# Generated by Django 4.1 on 2022-09-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия пользователя')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Administrator')], default='user', max_length=5, verbose_name='Роль')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
