# Generated by Django 4.1 on 2022-09-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_is_active_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
